// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMUausGvOVheYi7VRG04_MVoQklGj9jM4',
    appId: '1:395140475361:web:c7a9674ca123f4726c8aa0',
    messagingSenderId: '395140475361',
    projectId: 'enqvision-cse299',
    authDomain: 'enqvision-cse299.firebaseapp.com',
    storageBucket: 'enqvision-cse299.firebasestorage.app',
    measurementId: 'G-6S4E3DXE17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAarawMbD647oovz23grznUwo3TkgHe3IE',
    appId: '1:395140475361:android:adf56b7974f7d4746c8aa0',
    messagingSenderId: '395140475361',
    projectId: 'enqvision-cse299',
    storageBucket: 'enqvision-cse299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy3a7Og2Jk7R_imRbmYZQbfmXz0bMSnjc',
    appId: '1:395140475361:ios:8795905bff485d156c8aa0',
    messagingSenderId: '395140475361',
    projectId: 'enqvision-cse299',
    storageBucket: 'enqvision-cse299.firebasestorage.app',
    iosBundleId: 'com.example.enqvisionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy3a7Og2Jk7R_imRbmYZQbfmXz0bMSnjc',
    appId: '1:395140475361:ios:8795905bff485d156c8aa0',
    messagingSenderId: '395140475361',
    projectId: 'enqvision-cse299',
    storageBucket: 'enqvision-cse299.firebasestorage.app',
    iosBundleId: 'com.example.enqvisionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMUausGvOVheYi7VRG04_MVoQklGj9jM4',
    appId: '1:395140475361:web:707b1f8fd52c7b216c8aa0',
    messagingSenderId: '395140475361',
    projectId: 'enqvision-cse299',
    authDomain: 'enqvision-cse299.firebaseapp.com',
    storageBucket: 'enqvision-cse299.firebasestorage.app',
    measurementId: 'G-HMVB2XC2HQ',
  );
}
